version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    restart: always
    container_name: $DB_CONTAINER_NAME
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - mysql_db_2:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 3s
      retries: 5

  phpmyadmin-service:
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: phpmyadmin-ideas
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: $MYSQL_ROOT_PASSWORD
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
    # depends_on:
    #  mysql:
    #    condition: service_healthy
    links:
      - 'mysql:db'
    ports:
      - '8070:80'

  backend:
    image: node:21
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3300:3300"
    command: bash -c "cd /app && npm i -g prisma && prisma generate && prisma migrate dev --name init &&  npm i && npm run dev"

  frontend:
    image: node:latest
    working_dir: /app
    volumes:
      - ../frontend:/app
    ports:
      - "5000:5000"   # Cambiado el puerto 80 a 5000
    command: bash -c "cd /app && npm i && npm run dev  -- --host 0.0.0.0 --port 5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 5s
      timeout: 3s
      retries: 5
  

volumes:
  mysql_db_2:
